### PR TITLE
Use configurable routes

### PR DESCRIPTION
**Pull request by AnnikaCodes**
Similarly to my PR for the client, this will make it much easier to test.
I could also include routes from `$psconfig` in ../play.pokemonshowdown.com, but I presume it's better to make this standalone.

### CODE REVIEW

**Comment by monsanto** [comment]
@Zarel the staging environment is blocking on this PR, could you give it a look?

**Comment by Zarel** [comment]
I don't know what that means.

**Comment by Zarel** [comment]
Routes should probably inherit from `play.pokemonshowdown.com`.

Heck, the website itself should probably be a subdirectory on the client repo, the way Replays are. I think that would solve a lot of the problems here.

**Comment by AnnikaCodes** [comment]
> Routes should probably inherit from `play.pokemonshowdown.com`.
> 
> Heck, the website itself should probably be a subdirectory on the client repo, the way Replays are. I think that would solve a lot of the problems here.

Alrighty, should I create a PR for that then?

**Comment by Zarel** [comment]
What to call it? `website/`?

**Comment by Zarel** [comment]
I'm not _very_ opposed to a separate repository, but I don't really see the point of it.

I remember when we were discussing opening up the website repository, I said to put it in client, and then either pre or chaos made it a separate repository anyway. So maybe they know? @scheibo? @monsanto?

**Comment by scheibo** [comment]
It was purely made a separate repo purely for convenience of not needing to fuck with any of the routing

**Comment by Zarel** [comment]
Hm. Yeah, let's look into moving it in, then.

**Comment by AnnikaCodes** [comment]
Superseded by smogon/pokemon-showdown-client#1575.

**Pull request closed without merging**
